### ISSUE TITLE
.get/.set methods?

### ISSUE THREAD

**Issue by hornta** [lemire/TypedFastBitSet.js#12]
Hi, I'm coming from Javas where I would use the BitSet class to store my bits and I hoped this lib would be an equivalent of that. Can I do this with this library?
https://docs.oracle.com/javase/7/docs/api/java/util/BitSet.html#set(int)
https://docs.oracle.com/javase/7/docs/api/java/util/BitSet.html#get(int)

thanks

**Comment by lemire** [comment]
Please check our README, including code samples. If you still have questions then please be specific.

**Comment by hornta** [comment]
yea I watched that initially and it looked like it stored the actual value but then I checked out the source code and I saw it was the index

**Comment by lemire** [comment]
@hornta A bitset (whether in Java or in JavaScript) is a set of integers. You can also see it as an array of Booleans.

If you viewed it as an indexed set, then you'd want to provide an index *and* a Boolean value.
