### ISSUE TITLE
Version 0.4.0: No built files at all on NPM

### ISSUE THREAD

**Issue by aldipermanaetikaputra** [lemire/TypedFastBitSet.js#20]
<img width="904" alt="image" src="https://user-images.githubusercontent.com/77241979/221437849-365a3ea1-7bed-4afb-9cb3-8f92a2360ba2.png">

I tried to install the newest version of typedfastbitset, but was unable to import due to no "lib" folder.

**Comment by Codex-** [comment]
Yeah same issue, confusing script names (probably my fault lol), have made a PR to make it clearer
