### ISSUE TITLE
this.count property no longer available in 0.2.0

### ISSUE THREAD

**Issue by staltz** [lemire/TypedFastBitSet.js#7]
But it's still read in some cases https://github.com/lemire/TypedFastBitSet.js/blob/059a867806105d35d9bfd4ab4ad6f5d3d6bb4458/TypedFastBitSet.js#L343-L348 , which I believe will give undefined. For more context: https://github.com/ssb-ngi-pointer/jitdb/pull/88

**Comment by lemire** [comment]
Fixed in 0.2.1.
